// Package http Code generated by swaggo/swag. DO NOT EDIT
package http

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Skaotico"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/alertas": {
            "get": {
                "description": "Retorna la lista de alertas del sistema, con filtros opcionales",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alertas"
                ],
                "summary": "Listar alertas",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filtrar por UUID de sensor",
                        "name": "sensor_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por estado (e.g. activa, resuelta)",
                        "name": "estado",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Alerta"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/alertas/{id}/estado": {
            "put": {
                "description": "Actualiza el estado (activa, resuelta, etc.) y observaciones de una alerta",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alertas"
                ],
                "summary": "Actualizar estado de alerta",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID de la alerta",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos de actualización de la alerta",
                        "name": "estado",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateAlertaStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Alerta"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Verifica que el servicio Sensor está operativo",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check del servicio",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/sensores": {
            "get": {
                "description": "Retorna la lista de sensores filtrada opcionalmente por arbol_id o estanque_id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sensores"
                ],
                "summary": "Listar sensores",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filtrar por UUID de árbol",
                        "name": "arbol_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por UUID de estanque",
                        "name": "estanque_id",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filtrar por estado activo",
                        "name": "activo",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Sensor"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Registra un nuevo sensor de monitoreo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sensores"
                ],
                "summary": "Registrar un sensor",
                "parameters": [
                    {
                        "description": "Datos del sensor a registrar",
                        "name": "sensor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateSensorRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Sensor"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/sensores/{id}": {
            "get": {
                "description": "Retorna los datos detallados de un sensor específico",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sensores"
                ],
                "summary": "Obtener un sensor por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID del sensor",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Sensor"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Actualiza uno o más campos de un sensor existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sensores"
                ],
                "summary": "Actualizar un sensor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID del sensor",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Campos a actualizar",
                        "name": "sensor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateSensorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Sensor"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Elimina un sensor de la base de datos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sensores"
                ],
                "summary": "Eliminar un sensor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID del sensor",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/sensores/{id}/alertas": {
            "post": {
                "description": "Registra un evento de alerta disparado por un sensor",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alertas"
                ],
                "summary": "Registrar alerta de sensor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID del sensor",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos de la alerta",
                        "name": "alerta",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateAlertaRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Alerta"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/sensores/{id}/lecturas": {
            "get": {
                "description": "Retorna el histórico de lecturas reportadas por un sensor específico",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lecturas"
                ],
                "summary": "Listar lecturas de un sensor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID del sensor",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.LecturaSensor"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Registra una nueva lectura/medición reportada por un sensor",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lecturas"
                ],
                "summary": "Registrar lectura de sensor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID del sensor",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos de la lectura",
                        "name": "lectura",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateLecturaRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.LecturaSensor"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Alerta": {
            "type": "object",
            "properties": {
                "estado": {
                    "type": "string"
                },
                "fecha_alerta": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "observacion": {
                    "type": "string"
                },
                "sensor_id": {
                    "type": "string"
                },
                "tipo": {
                    "type": "string"
                },
                "umbral": {
                    "type": "number"
                },
                "valor_detectado": {
                    "type": "number"
                }
            }
        },
        "model.CreateAlertaRequest": {
            "type": "object",
            "properties": {
                "fecha_alerta": {
                    "type": "string"
                },
                "observacion": {
                    "type": "string"
                },
                "tipo": {
                    "type": "string"
                },
                "umbral": {
                    "type": "number"
                },
                "valor_detectado": {
                    "type": "number"
                }
            }
        },
        "model.CreateLecturaRequest": {
            "type": "object",
            "properties": {
                "bateria_porcentaje": {
                    "type": "integer"
                },
                "fecha_lectura": {
                    "type": "string"
                },
                "observacion": {
                    "type": "string"
                },
                "valor": {
                    "type": "number"
                }
            }
        },
        "model.CreateSensorRequest": {
            "type": "object",
            "properties": {
                "arbol_id": {
                    "type": "string"
                },
                "codigo": {
                    "type": "string"
                },
                "estanque_id": {
                    "type": "string"
                },
                "fabricante": {
                    "type": "string"
                },
                "fecha_instalacion": {
                    "type": "string"
                },
                "modelo": {
                    "type": "string"
                },
                "tipo_sensor_id": {
                    "type": "string"
                }
            }
        },
        "model.LecturaSensor": {
            "type": "object",
            "properties": {
                "bateria_porcentaje": {
                    "type": "integer"
                },
                "fecha_lectura": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "observacion": {
                    "type": "string"
                },
                "sensor_id": {
                    "type": "string"
                },
                "valor": {
                    "type": "number"
                }
            }
        },
        "model.Sensor": {
            "type": "object",
            "properties": {
                "activo": {
                    "type": "boolean"
                },
                "arbol_id": {
                    "type": "string"
                },
                "codigo": {
                    "type": "string"
                },
                "estanque_id": {
                    "type": "string"
                },
                "fabricante": {
                    "type": "string"
                },
                "fecha_instalacion": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "modelo": {
                    "type": "string"
                },
                "tipo_sensor_id": {
                    "type": "string"
                }
            }
        },
        "model.UpdateAlertaStatusRequest": {
            "type": "object",
            "properties": {
                "estado": {
                    "type": "string"
                },
                "observacion": {
                    "type": "string"
                }
            }
        },
        "model.UpdateSensorRequest": {
            "type": "object",
            "properties": {
                "activo": {
                    "type": "boolean"
                },
                "arbol_id": {
                    "type": "string"
                },
                "codigo": {
                    "type": "string"
                },
                "estanque_id": {
                    "type": "string"
                },
                "fabricante": {
                    "type": "string"
                },
                "fecha_instalacion": {
                    "type": "string"
                },
                "modelo": {
                    "type": "string"
                },
                "tipo_sensor_id": {
                    "type": "string"
                }
            }
        },
        "response.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "response.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/response.APIError"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9096",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Homelab Platform - API Sensor",
	Description:      "Microservicio de gestión de sensores (iot.sensor, readings, alerts). Parte de la Homelab Collector Platform.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
